Repository angular/vscode-ng-language-service, pull requests merged in 2021-10, with the labels that each got.

#1512 build(language-server): update to TypeScript 4.4
  package.json
  server/src/session.ts
  server/tsconfig.json
  yarn.lock
Labels: target: major, action: merge, cla: yes

#1516 build: update dependency to latest v13 release and fix errors
  integration/lsp/ivy_spec.ts
  integration/lsp/viewengine_spec.ts
  integration/tsconfig.json
  package.json
  server/package.json
  server/src/session.ts
  server/src/tests/tsconfig.json
  server/src/version_provider.ts
  syntaxes/test/cases.json
  syntaxes/test/cases.ts
  syntaxes/test/driver.ts
  tsconfig.json
  yarn.lock
Labels: target: major, action: merge, cla: yes

#1518 refactor: update to angular v13 with APF v13 output
  .circleci/config.yml
  integration/lsp/ivy_spec.ts
  integration/lsp/test_utils.ts
  integration/project/package.json
  integration/project/yarn.lock
  integration/test_constants.ts
  integration/workspace/package.json
  integration/workspace/yarn.lock
  package.json
  scripts/build.sh
  scripts/test.sh
  server/src/ngcc.ts
  server/src/session.ts
  server/src/tests/ngcc_spec.ts
  server/src/version_provider.ts
  yarn.lock
Labels: target: major, action: merge, cla: yes

#1509 feat: provide snippets for attribute
  client/src/client.ts
  integration/lsp/ivy_spec.ts
  integration/lsp/test_utils.ts
  package.json
  server/src/cmdline_utils.ts
  server/src/completion.ts
  server/src/server.ts
  server/src/session.ts
Labels: target: minor, action: merge, cla: yes

#1523 refactor: support resolving ngcc from APF v13 output
  .circleci/config.yml
  integration/apf_project/app/app.component.ts
  integration/apf_project/app/app.module.ts
  integration/apf_project/app/foo.component.html
  integration/apf_project/app/foo.component.ts
  integration/apf_project/package.json
  integration/apf_project/tsconfig.json
  integration/apf_project/yarn.lock
  scripts/test.sh
  server/src/ngcc.ts
  server/src/tests/ngcc_spec.ts
  server/src/version_provider.ts
Labels: target: patch, action: merge, cla: yes

#1527 refactor(client): Support VE by using the v12 version of the language…
  .circleci/config.yml
  client/src/client.ts
  package.json
  scripts/build.sh
  server/src/session.ts
  v12_language_service/package.json
  v12_language_service/yarn.lock
Labels: target: major, action: merge, cla: yes

#1533 fix: add requirement in the `includeAutomaticOptionalChainCompletions…
  package.json
Labels: target: major, action: merge, cla: yes
