Repository angular/vscode-ng-language-service, pull requests merged in 2021-04, with the labels that each got.

#1244 build: set up ng-dev toolset for the repo
  .gitignore
  .ng-dev/config.ts
  .ng-dev/github.ts
  .ng-dev/merge.ts
  package.json
  yarn.lock
Labels: action: merge, cla: yes, target: major

#1247 build: set up ng-dev toolset for the repo
  .gitignore
  .ng-dev/config.ts
  .ng-dev/github.ts
  .ng-dev/merge.ts
  package.json
  yarn.lock
Labels: action: merge, cla: yes, target: patch

#1246 build: add configuration to launch prod client
  .vscode/launch.json
  .vscode/tasks.json
Labels: cla: yes, target: patch

#1252 build: update vscode to 1.55
  integration/e2e/index.ts
  package.json
  yarn.lock
Labels: cla: yes

#1260 fix: do not resolve CodeLens command until LS is enabled
  server/src/session.ts
Labels: action: merge, cla: yes, target: minor

#1262 build: fix compound target in launch.json
  .vscode/launch.json
Labels: action: merge, cla: yes, target: patch

#1259 perf: Avoid making Angular-related decisions for files not in an Angu…
  client/src/client.ts
  common/requests.ts
  integration/lsp/ivy_spec.ts
  server/src/session.ts
Labels: action: merge, cla: yes, target: major

#1272 perf: Avoid making Angular-related decisions for files not in an Angular project
  client/src/client.ts
  common/requests.ts
  integration/lsp/ivy_spec.ts
  server/src/session.ts
Labels: cla: yes, target: patch

#1279 fix: make Ivy LS the default
  client/src/client.ts
  integration/lsp/test_utils.ts
  integration/project/.vscode/settings.json
  package.json
  server/src/cmdline_utils.ts
Labels: cla: yes, cleanup, target: major

#1273 docs: add instructions to enable verbose logging in bug reports
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: action: merge, cla: yes, target: patch

#1282 ci: fix flaky e2e test
  .github/workflows/node.js.yml
Labels: action: merge, cla: yes, target: major

#1281 refactor: wrap server script in main() to avoid polluting globals
  server/src/server.ts
Labels: cla: yes, target: major

#1277 feat: add support for signature help
  client/src/client.ts
  integration/lsp/ivy_spec.ts
  package.json
  server/src/session.ts
  server/src/utils.ts
  yarn.lock
Labels: action: merge, cla: yes, target: major

#1288 fix: pass watch options to watchFile and watchDirectory
  server/src/server_host.ts
Labels: action: merge, cla: yes, target: patch

#1295 refactor: replace logPath with logUri
  client/src/client.ts
Labels: cla: yes, target: major

#1294 fix: set minimum TS version to 4.2
  server/src/version_provider.ts
Labels: cla: yes, target: major

#1296 refactor: remove suggest Ivy LS notification
  client/src/client.ts
  common/notifications.ts
  integration/lsp/viewengine_spec.ts
  server/src/session.ts
Labels: cla: yes, target: major

#1297 chore: add vim swap files to .gitignore
  .gitignore
Labels: action: merge, cla: yes, target: patch

#1299 fix: Use View Engine LS for projects < v9
  client/src/client.ts
Labels: cla: yes, target: major

#1300 docs: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: action: merge, cla: yes, target: major
