Repository angular/vscode-ng-language-service, pull requests merged in 2021-05, with the labels that each got.

#1323 fix: remove TSC_NONPOLLING_WATCHER env variable and provide default w…
  client/src/client.ts
  integration/lsp/test_utils.ts
  server/src/server.ts
  server/src/session.ts
Labels: action: merge, cla: yes, target: major

#1326 fix: remove TSC_NONPOLLING_WATCHER env variable and provide default watchOptions
  client/src/client.ts
  integration/lsp/test_utils.ts
  server/src/server.ts
  server/src/session.ts
Labels: action: merge, cla: yes, target: patch

#1331 fix: files incorrectly determined as not being in an Angular project
  client/src/client.ts
Labels: action: merge, cla: yes, target: patch

#1342 docs: add note about compiler options to readme
  README.md
Labels: action: merge, cla: yes, target: major

#1343 build: bump vscode to 1.56.0
  integration/e2e/index.ts
  package.json
  yarn.lock
Labels: cla: yes, target: major

#1344 test: update FW packages in test projects to v12
  integration/project/package.json
  integration/project/yarn.lock
  integration/workspace/package.json
  integration/workspace/yarn.lock
Labels: action: merge, cla: yes, target: patch

#1337 feat: Allow renaming from string literals in TS files
  client/src/client.ts
  client/src/embedded_support.ts
  integration/lsp/ivy_spec.ts
  server/src/session.ts
Labels: action: merge, cla: yes, target: minor

#1358 fix: check Angular version if angular.view-engine is false
  client/src/client.ts
Labels: action: merge, cla: yes, target: patch

#1359 fix: remove message about disabled LS if ngcc fails
  server/src/session.ts
Labels: action: merge, cla: yes, target: patch

#1361 fix: remove angular.ngdk configuration
  README.md
  client/src/client.ts
  package.json
Labels: action: merge, cla: yes, target: patch

#1360 perf: Avoid making Angular-related decisions for files not in an Angu…
  client/src/client.ts
  common/requests.ts
  server/src/session.ts
Labels: action: merge, cla: yes, target: patch

#1370 fix: avoid showing MISSING: command for code lens in templates
  server/src/session.ts
Labels: action: merge, cla: yes, target: patch

#1369 fix: only give html provider completions for inline templates
  client/src/client.ts
  integration/e2e/completion_spec.ts
  integration/e2e/helper.ts
  integration/e2e/hover_spec.ts
  integration/project/app/foo.component.html
Labels: action: merge, cla: yes, target: patch

#1375 fix: bad merge caused build failure
  server/src/session.ts
Labels: action: merge, cla: yes, target: patch

#1376 fix: support nullish coalesce for syntax highlighting
  syntaxes/expression.json
  syntaxes/src/expression.ts
  syntaxes/test/data/expression.html
  syntaxes/test/data/expression.html.snap
  syntaxes/test/data/template.html
  syntaxes/test/data/template.html.snap
Labels: action: merge, cla: yes, target: patch
