Repository angular/vscode-ng-language-service, pull requests merged in 2021-03, with the labels that each got.

#1182 perf: yield after checking diagnostics for an open file
  server/src/session.ts
  server/src/utils.ts
Labels: perf

#1180 perf: prevent requests from being sent to the server when outside Angular context
  .vscode/launch.json
  client/src/client.ts
  client/src/embedded_support.ts
  client/src/tests/embedded_support_spec.ts
  client/src/tests/tsconfig.json
  client/tsconfig.json
  jasmine.json
  package.json
  yarn.lock
Labels: extension, ivy, perf, user XP, view engine

#1166 feat: Add codelens with a link to go to the component from a template
  integration/lsp/ivy_spec.ts
  server/src/session.ts
Labels: cleanup, feature, ivy, user XP

#1212 feat: forward completion and hover requests to html providers for inl…
  client/src/client.ts
Labels: extension, feature, user XP
