Repository angular/vscode-ng-language-service, pull requests merged in 2021-02, with the labels that each got.

#1065 feat: Add renaming capability
  integration/lsp/ivy_spec.ts
  integration/lsp/test_utils.ts
  integration/lsp/viewengine_spec.ts
  integration/project/app/app.component.ts
  package.json
  server/src/session.ts
  yarn.lock
Labels: feature, ivy

#1098 fix: ngcc progress not reported
  server/src/ngcc.ts
Labels: bug, ivy

#1129 fix: remove TSC_NONPOLLING_WATCHER env variable
  client/src/client.ts
  integration/lsp/test_utils.ts
  server/src/server.ts
Labels: patch
