Repository angular/vscode-ng-language-service, pull requests merged in 2021-11, with the labels that each got.

#1546 chore: Update vscode version in package.json
  integration/e2e/index.ts
  package.json
  yarn.lock
Labels: target: major, action: merge, cla: yes

#1549 build: Downgrade vscode version to last supported g3 version
  integration/e2e/index.ts
  package.json
  yarn.lock
Labels: target: major, action: merge, cla: yes

#1552 build: Update versions to the -next release after 13.0.x branch
  package.json
  server/package.json
  yarn.lock
Labels: target: minor, action: merge, cla: yes

#1567 ci: setup scheduled CI job to test repository against the latest builds
  .circleci/config.yml
  .github/workflows/node.js.yml
  scripts/build.sh
Labels: target: patch, action: merge, cla: yes

#1571 test: fix syntax tests so they work when testing against builds repo
  scripts/test.sh
Labels: target: patch, action: merge, cla: yes
