Repository angular/vscode-ng-language-service, pull requests merged in 2022-11, with the labels that each got.

#1797 build: do not manage package version in Starlark file
  .bazelrc
  BUILD.bazel
  package.json
  scripts/build.sh
  server/BUILD.bazel
  version.bzl
Labels: target: patch, action: merge

#1798 build: update main version to target 15.0
  package.json
Labels: target: minor, action: merge

#1794 build: update build.sh script for bazel
  scripts/build.sh
Labels: target: patch, action: merge

#1793 fix(build): Adjust pointers to bazel-built directory
  .vscode/launch.json
  .vscode/tasks.json
  BUILD.bazel
  DEVELOPER.md
  client/src/client.ts
  package.json
Labels: target: minor, action: merge

#1801 build: resolve dependency issues with built vsix
  BUILD.bazel
  package.json
  server/package.json
  server/src/version_provider.ts
  yarn.lock
Labels: target: minor, action: merge

#1802 build: update main to target 15.1
  package.json
  server/package.json
Labels: target: minor

#1804 docs: cherry-pick v15 release notes
  CHANGELOG.md
Labels: target: minor, area: docs

#1806 Cherry pick fixes from #1801
  BUILD.bazel
  package.json
  server/package.json
  server/src/version_provider.ts
  yarn.lock
Labels: target: patch, action: merge

#1807 release: v15.0.1
  CHANGELOG.md
  package.json
Labels: target: patch, action: merge

#1808 docs: cherry pick 15.0.1 release notes
  CHANGELOG.md
Labels: target: minor, action: merge, area: docs

#1809 chore: update to the latest Aspect rules_js, rules_ts, rules_jasmine & rules_esbuild
  WORKSPACE
  package.json
  yarn.lock
Labels: target: patch, action: merge

#1813 testing: fix task endPattern for iBazel
  .vscode/tasks.json
Labels: target: patch, action: merge

#1816 fix: fix "install local @angular/language-service" workflow under Bazel build
  .bazelrc
  .gitignore
  WORKSPACE
Labels: target: patch, action: merge

#1814 chore: update to aspect_rules_ts 1.0.0
  WORKSPACE
Labels: target: patch, action: merge

#1817 build: update to rules_js 1.7.0
  WORKSPACE
Labels: target: patch, action: merge

#1823 build: fix .bazelrc --build_test_only flag
  .bazelrc
Labels: target: patch, action: merge

#1825 build: add missing vscode-nls to npm_translate_lock hoisted package
  WORKSPACE
Labels: target: patch, action: merge

#1826 fix: add v12_language_service/node_modules to release package
  .bazelignore
  WORKSPACE
  pnpm-workspace.yaml
  v12_language_service/BUILD.bazel
Labels: target: patch, action: merge

#1830 release: v15.0.2
  CHANGELOG.md
  package.json
  server/package.json
  yarn.lock
Labels: target: patch
