Repository angular/vscode-ng-language-service, pull requests merged in 2022-06, with the labels that each got.

#1681 build: update main branch after 14.0.0 release
  CHANGELOG.md
  integration/project/package.json
  integration/project/yarn.lock
  package.json
  server/package.json
  yarn.lock
Labels: target: minor, action: merge

#1687 fix(extension): disable rename override to allow built in TS renaming
  client/src/client.ts
  override_rename_ts_plugin/README.md
  package.json
  scripts/build.sh
  yarn.lock
Labels: target: patch, action: merge

#1689 release: v14.0.1
  CHANGELOG.md
  package.json
  server/package.json
Labels: target: patch

#1691 build: update targets to 14.1.0-next.0
  integration/project/package.json
  integration/project/yarn.lock
  package.json
  server/package.json
  yarn.lock
Labels: target: minor, action: merge

#1695 feat(extension): Update untrusted workspace support from 'false' to '…
  client/src/client.ts
  package.json
  server/src/cmdline_utils.ts
  server/src/server.ts
  server/src/session.ts
Labels: target: minor, action: merge

#1703 build: avoid use of ts-node wrapper script as it breaks child process forking
  package.json
  yarn.lock
Labels: target: minor, action: merge
