Repository angular/vscode-ng-language-service, pull requests merged in 2022-10, with the labels that each got.

#1754 build: run bazel tests on CI and generate bazel built dist/npm_bazel folder
  .bazelrc
  .circleci/config.yml
  .gitignore
  .npmrc
  BUILD.bazel
  WORKSPACE
  integration/e2e/BUILD.bazel
  integration/e2e/completion_spec.ts
  integration/e2e/jasmine.ts
  package.json
  scripts/build.sh
  scripts/test.sh
  syntaxes/BUILD.bazel
  syntaxes/src/BUILD.bazel
  syntaxes/src/build.ts
  version.bzl
Labels: target: patch, action: merge

#1776 build: cut-over dist/npm to bazel built artifacts
  scripts/build.sh
Labels: target: patch, action: merge

#1779 feat(server): provide folding ranges for inline templates
  BUILD.bazel
  client/src/client.ts
  esbuild.js
  integration/lsp/ivy_spec.ts
  integration/lsp/viewengine_spec.ts
  package.json
  server/BUILD.bazel
  server/package.json
  server/src/BUILD.bazel
  server/src/banner.ts
  server/src/embedded_support.ts
  server/src/session.ts
  server/src/tests/embedded_support_spec.ts
  yarn.lock
Labels: feature, target: minor, action: merge

#1795 ci: update node version for CI to latest v14
  .circleci/config.yml
  .nvmrc
Labels: target: patch, action: merge

#1796 build: Update package.json to use bazel VERSION constant
  BUILD.bazel
  package.json
  server/BUILD.bazel
  server/package.json
Labels: target: minor, action: merge
