Repository angular/vscode-ng-language-service, pull requests merged in 2022-01, with the labels that each got.

#1575 fix: Prevent legacy VE from being used with v13 projects
  client/src/client.ts
  package.json
Labels: target: patch, action: merge, cla: yes

#1598 build: revert updating node version
  package.json
  server/package.json
  yarn.lock
Labels: target: minor, action: merge, cla: yes

#1599 test: fix integration tests to tolerate slight label changes
  integration/lsp/ivy_spec.ts
Labels: target: patch, action: merge, cla: yes

#1603 build: update versions to -next after 13.2.x branch
  package.json
  server/package.json
  yarn.lock
Labels: target: major, action: merge, cla: yes

#1604 fix(server): return the right range for the original source file of DTS
  server/src/session.ts
Labels: target: patch, action: merge, cla: yes
