Repository angular/vscode-ng-language-service, pull requests merged in 2022-04, with the labels that each got.

#1621 feat: add command to run ngcc manually
  client/src/client.ts
  client/src/commands.ts
  common/requests.ts
  package.json
  server/src/cmdline_utils.ts
  server/src/server.ts
  server/src/session.ts
Labels: target: minor, action: merge, cla: yes

#1622 fix: Correct syntax highlighting for style.prop.%
  syntaxes/src/template.ts
  syntaxes/template.json
  syntaxes/test/data/template.html
  syntaxes/test/data/template.html.snap
Labels: target: patch, action: merge, cla: yes

#1627 fix(server): Ensure all projects that finish ngcc re-enable language …
  server/src/session.ts
Labels: target: patch, action: merge, cla: yes

#1637 build: update configuration for ng-dev
  .ng-dev/merge.ts
  package.json
  yarn.lock
Labels: target: patch, action: merge

#1639 fix(dev-infra): fix ng-dev configuration
  .ng-dev/config.ts
  .ng-dev/format.ts
  .ng-dev/github.ts
  .ng-dev/pullRequest.ts
Labels: target: minor, action: merge, cla: yes

#1641 Revert "chore(deps): update dependency jasmine to v4 (#1592)"
  package.json
  yarn.lock
Labels: target: patch, action: merge
