Repository angular/vscode-ng-language-service, pull requests merged in 2022-09, with the labels that each got.

#1750 Disable bazel-build-and-test CircleCI job; not yet load bearing
  .circleci/config.yml
Labels: target: minor, action: merge

#1749 build: update to TS 4.8.2 and Angular 14.2.0.
  package.json
  server/package.json
  yarn.lock
Labels: target: minor, action: merge

#1751 release: v14.2.0
  CHANGELOG.md
  package.json
  server/package.json
Labels: target: minor, action: merge

#1747 fix(server): send diagnostic range to the Angular language service wh…
  integration/lsp/ivy_spec.ts
  server/src/session.ts
Labels: target: minor, action: merge

#1758 Update main branch to target 15
  integration/project/package.json
  integration/project/yarn.lock
  package.json
  server/package.json
  yarn.lock
Labels: target: major, action: merge

#1765 fix(server): resolve tsdk correctly when settings specify a relative …
  server/src/version_provider.ts
Labels: target: patch, action: merge
