Repository angular/vscode-ng-language-service, pull requests merged in 2022-05, with the labels that each got.

#1646 feat(extension): Add option to force strict templates
  client/src/client.ts
  package.json
  server/src/cmdline_utils.ts
  server/src/server.ts
  server/src/session.ts
Labels: target: minor, action: merge

#1651 build: clean up references to old `master` branch
  CHANGELOG.md
  README.md
  override_rename_ts_plugin/README.md
  package.json
  syntaxes/README.md
Labels: target: minor, action: merge

#1654 release: v13.3.3
  CHANGELOG.md
  package.json
  server/package.json
  yarn.lock
Labels: action: merge

#1655 fix(docs): Fix the link to the demo after branch rename
  README.md
Labels: target: patch, action: merge

#1658 fix(language-server): Fix detection of Angular for v14+ projects
  server/src/session.ts
Labels: target: patch, action: merge

#1660 fix(language-server): Fix detection of Angular for v14+ projects
  server/src/session.ts
Labels: target: patch, action: merge

#1661 release: v13.3.4
  CHANGELOG.md
  package.json
  server/package.json
  yarn.lock
Labels: target: patch, action: merge

#1665 build: update vscode version
  integration/e2e/index.ts
  package.json
  yarn.lock
Labels: target: minor, action: merge

#1663 release: v14.0.0-rc.0
  CHANGELOG.md
  package.json
  server/package.json
  yarn.lock
Labels: target: major, action: merge

#1669 fix(language-server): Ensure diagnostics are refreshed when language …
  server/src/session.ts
Labels: target: patch, action: merge

#1659 test: Update integration project to target v14
  integration/lsp/ivy_spec.ts
  integration/project/package.json
  integration/project/yarn.lock
Labels: target: major, action: merge

#1677 build: set up post approval changes commit action
  .github/workflows/dev-infra.yml
Labels: target: patch, action: merge
