Repository angular/vscode-ng-language-service, pull requests merged in 2023-01, with the labels that each got.

#1838 docs: Cherry pick release notes from v15 patches
  CHANGELOG.md
Labels: target: minor, action: merge, area: docs

#1845 release: v15.0.4
  CHANGELOG.md
  package.json
  server/package.json
  yarn.lock
Labels: target: patch

#1846 build: update angular/angular packages/language-service/build.sh placeholder
  WORKSPACE
Labels: target: patch, action: merge

#1851 build: update main to target 15.2.0
  CHANGELOG.md
  package.json
  server/package.json
  yarn.lock
Labels: target: minor

#1849 feat: Add option to disable code actions
  client/src/client.ts
  package.json
  server/src/cmdline_utils.ts
  server/src/server.ts
  server/src/session.ts
Labels: target: minor, action: merge, detected: feature

#1854 release: v15.2.0-next.0
  CHANGELOG.md
  package.json
  server/package.json
  yarn.lock
Labels: target: minor
