Repository angular/vscode-ng-language-service, pull requests merged in 2023-03, with the labels that each got.

#1875 Respect the client capability "textDocument.definition.linkSupport."
  integration/lsp/test_utils.ts
  server/src/session.ts
Labels: target: patch, action: merge

#1876 build: bump VSCode version
  integration/e2e/index.ts
  package.json
Labels: target: patch, action: merge

#1884 build: update pnpm lock file
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  pnpm-lock.yaml
Labels: action: merge

#1883 release: v16.0.0-next.0
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
  server/package.json
  yarn.lock
Labels: target: major
