Repository angular/vscode-ng-language-service, pull requests merged in 2023-11, with the labels that each got.

#1954 docs: update logo
  angular.png
Labels: target: patch, action: merge, area: docs

#1955 release: v17.0.0
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  CHANGELOG.md
  WORKSPACE
  package.json
  pnpm-lock.yaml
  server/package.json
  yarn.lock
Labels: target: major, action: merge

#1960 fix(syntaxes): Use expression.ng instead of JS for block expressions
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  package.json
  syntaxes/src/template-blocks.ts
  syntaxes/template-blocks.json
  syntaxes/test/cases.ts
  syntaxes/test/data/template-blocks.html
  syntaxes/test/data/template-blocks.html.snap
Labels: target: minor, action: merge

#1961 fix(syntaxes): Adjust block syntax highlighting to require ( or { on …
  syntaxes/src/template-blocks.ts
  syntaxes/template-blocks.json
  syntaxes/test/data/template-blocks.html
  syntaxes/test/data/template-blocks.html.snap
Labels: target: major, action: merge

#1956 fix(syntaxes): Single quote should end `as` alias match
  syntaxes/expression.json
  syntaxes/src/expression.ts
  syntaxes/test/data/expression.html
  syntaxes/test/data/expression.html.snap
Labels: target: minor, action: merge

#1963 build: Update main to target 17.1
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  package.json
  pnpm-lock.yaml
Labels: target: minor

#1962 fix: Disable block syntax parsing when no project in workspace suppor…
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  client/src/client.ts
  package.json
  pnpm-lock.yaml
  server/package.json
  server/src/cmdline_utils.ts
  server/src/server.ts
  server/src/session.ts
  yarn.lock
Labels: target: minor, action: merge

#1964 fix: Disable block syntax parsing when no project in workspace suppor…
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  client/src/client.ts
  package.json
  pnpm-lock.yaml
  server/package.json
  server/src/cmdline_utils.ts
  server/src/server.ts
  server/src/session.ts
  yarn.lock
Labels: target: patch, action: merge

#1965 release: v17.0.1
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  CHANGELOG.md
  package.json
Labels: target: patch

#1892 Update README.md
  README.md
Labels: target: patch, action: merge

#1969 build: Update rules_js
  WORKSPACE
Labels: target: patch, action: merge

#1972 fix(server): Do not disable language service for solution style root tsconfig
  server/src/session.ts
Labels: target: patch, action: merge

#1970 fix(client,server): Correctly use bundled version unless tsdk is specified
  client/src/client.ts
  server/src/banner.ts
  server/src/cmdline_utils.ts
  server/src/server.ts
  server/src/tests/version_provider_spec.ts
  server/src/version_provider.ts
Labels: target: patch, action: merge

#1976 build: update nodeJS version in WORKSPACE
  WORKSPACE
Labels: target: minor

#1975 docs: cherry-pick release notes for 17.0.1 and 2
  CHANGELOG.md
Labels: target: minor, area: docs
