Repository angular/vscode-ng-language-service, pull requests merged in 2023-10, with the labels that each got.

#1929 build: create v17.0.0-next.0 release
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  .circleci/config.yml
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
  server/package.json
  yarn.lock
Labels: target: minor, action: merge

#1931 release: Release v17.0.0-next.1
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
  server/package.json
  yarn.lock
Labels: target: minor

#1932 build: update integration project version to v17
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE5NDc2NjEwNDI=
  integration/project/package.json
  integration/project/pnpm-lock.yaml
  integration/project/yarn.lock
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: target: minor, action: merge

#1928 build: Move 'test' package to dev dependencies
  server/package.json
Labels: target: patch, action: merge

#1904 fix: support to show the tag info in the jsDoc
  client/src/client.ts
  client/src/commands.ts
  common/initialize.ts
  server/src/session.ts
  server/src/tests/text_render_spec.ts
  server/src/text_render.ts
Labels: target: patch, action: merge

#1937 feat: support block completions
  server/src/completion.ts
  server/src/session.ts
Labels: target: major, action: merge, detected: feature

#1936 docs: merge release notes from 16.2.0 into main
  CHANGELOG.md
Labels: target: minor, action: merge, area: docs

#1938 feat(server): Add folding range support for Angular template syntax
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  client/src/client.ts
  integration/lsp/ivy_spec.ts
  package.json
  pnpm-lock.yaml
  server/package.json
  server/src/session.ts
  yarn.lock
Labels: target: minor, action: merge, detected: feature

#1939 release: v17.0.0-next.2
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  CHANGELOG.md
  package.json
Labels: target: minor

#1942 refactor(client): Show warning message if a project uses a newer vers…
  client/src/client.ts
  common/resolver.ts
Labels: target: minor, action: merge

#1943 refactor(client): Show warning message if a project uses a newer vers…
  client/src/client.ts
  common/resolver.ts
Labels: target: patch

#1947 fix(syntaxes): Support multiline block expressions
  syntaxes/src/template-blocks.ts
  syntaxes/template-blocks.json
  syntaxes/test/data/template-blocks.html
  syntaxes/test/data/template-blocks.html.snap
Labels: target: minor
