Repository angular/vscode-ng-language-service, pull requests merged in 2024-06, with the labels that each got.

#2039 update main to target 18.1
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  package.json
  pnpm-lock.yaml
  server/package.json
  yarn.lock
Labels: target: minor, area: build & ci

#2040 build: update main to target 18.1
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  package.json
Labels: target: minor, area: build & ci

#2038 Revert "refactor(client): use SourceFile to detect the Angular contex…
  client/src/embedded_support.ts
  client/src/tests/embedded_support_spec.ts
Labels: target: patch, action: merge

#2042 feat(syntaxes): add support for let declarations
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  package.json
  pnpm-lock.yaml
  syntaxes/BUILD.bazel
  syntaxes/let-declaration.json
  syntaxes/src/build.ts
  syntaxes/src/template-let-declaration.ts
  syntaxes/test/cases.ts
  syntaxes/test/data/let-declaration.html
  syntaxes/test/data/let-declaration.html.snap
Labels: target: minor, action: merge, detected: feature

#2031 feat: generate the import declaration for the completion item code ac…
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  .circleci/config.yml
  client/src/client.ts
  client/src/commands.ts
  integration/lsp/ivy_spec.ts
  integration/project/app/bar.component.ts
  integration/test_constants.ts
  package.json
  pnpm-lock.yaml
  server/package.json
  server/src/session.ts
  yarn.lock
Labels: cleanup, target: minor, detected: feature

#2047 fix(server): disable let syntax when not supported
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  client/src/client.ts
  package.json
  pnpm-lock.yaml
  server/src/cmdline_utils.ts
  server/src/server.ts
  server/src/session.ts
  yarn.lock
Labels: target: minor
