Repository angular/vscode-ng-language-service, pull requests merged in 2025-02, with the labels that each got.

#2141 build: update main branch to 19.1
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  package.json
  pnpm-lock.yaml
  server/package.json
  yarn.lock
Labels: target: minor, action: merge, area: build & ci

#2136 fix(extension): Fix grouping of Angular commands into submenu
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  package.json
  pnpm-lock.yaml
Labels: target: minor, action: merge

#2142 fix: replace the closing symbol for inputs/outputs.
  server/src/completion.ts
  server/src/session.ts
Labels: target: minor, action: merge

#2144 release: create release notes for 19.1.0
  CHANGELOG.md
Labels: target: minor

#2145 build: bump main branch to 19.2
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  package.json
  pnpm-lock.yaml
  server/package.json
  yarn.lock
Labels: target: minor, area: build & ci

#2098 docs: update nvim-lspconfig link
  README.md
Labels: target: patch, action: merge, area: docs
