Repository angular/vscode-ng-language-service, pull requests merged in 2025-03, with the labels that each got.

#2152 feat(syntaxes): support template literals
  syntaxes/expression.json
  syntaxes/src/expression.ts
  syntaxes/test/data/expression.html
  syntaxes/test/data/expression.html.snap
Labels: target: minor, action: merge, detected: feature, area: build & ci

#2154 build: update language-service version and bump version for release
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  CHANGELOG.md
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: area: build & ci

#2155 feat: add support for host bindings
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  client/src/client.ts
  client/src/embedded_support.ts
  integration/project/tsconfig.json
  integration/workspace/tsconfig.json
  package.json
  pnpm-lock.yaml
  syntaxes/BUILD.bazel
  syntaxes/host-object-literal.json
  syntaxes/src/build.ts
  syntaxes/src/host-object-literal.ts
  syntaxes/test/cases.ts
  syntaxes/test/data/host-object-literal.ts
  syntaxes/test/data/host-object-literal.ts.snap
Labels: target: minor, action: merge, detected: feature

#2163 build: cut v19.2.2 version of language service
  .aspect/rules/external_repository_action_cache/npm_translate_lock_LTE4Nzc1MDcwNjU=
  CHANGELOG.md
  client/src/tests/embedded_support_spec.ts
  package.json
  pnpm-lock.yaml
  server/package.json
  yarn.lock
Labels: target: patch, area: build & ci

#2162 fix(syntaxes): Semicolons not tokenized
  syntaxes/expression.json
  syntaxes/src/expression.ts
  syntaxes/test/data/expression.html.snap
  syntaxes/test/data/template-blocks.html.snap
  syntaxes/test/data/template-tag.html.snap
Labels: target: minor, action: merge
